### ISSUE TITLE
Front page masonry not always correct in Chrome

### ISSUE THREAD

**Issue by petervanderdoes** [Zenithar/hugo-theme-bleak#12]
When using Chrome on Linux, can't test other OS, the masonry layout on the front page is sometimes messed up, the articles overlap. Reloading the page sometimes fixes it but reloading it again will reintroduce the problem

The screen shot is taken from your own site.

![masonry-bug](https://cloud.githubusercontent.com/assets/380071/15810926/52ac12ba-2b71-11e6-9efc-d3363e26c329.jpg)

**Comment by Zenithar** [comment]
I know this problem it's due to async loading.

**Comment by Zenithar** [comment]
It should be correct now, no async loading by now, I use preloader.
