### ISSUE TITLE
issue with post images with theme

### ISSUE THREAD

**Issue by nayibor** [Zenithar/hugo-theme-bleak#17]
great hugo theme .very cool!!.

i was using images for my posts and  placed them in the static/images directory but the images don't show up as a post image.
i traced it down to the li file  layouts/_default/li.html  in the theme. 
this section 
`<a href="{{ .Permalink }}"><img src="{{ .Params.image }}" alt="" /></a>
`
i changed it to 
`
<a href="{{ .Permalink }}"><img src="images/{{ .Params.image }}" alt="" /></a>
`
in my layouts/_defaut/li.html and that seemed to do the  trick .
dont know if its an intentional feature meant to make it more flexible and allowing you to place the images anywhere ??
thanks .

**Comment by Zenithar** [comment]
Hi,

Thanks, It's not my theme, I have just proted it from Ghost to Hugo, but thanks ^^

It's not an intentional feature, but it fits my needs ^^ If not, you have modified it to fit yours : OpenSource rules ! 

No problem with that.

**Comment by nayibor** [comment]
yep .
right u are .
maybe have to create a fork and tweak it to my liking .
thanks !!

**Comment by Zenithar** [comment]
No you can close ^^ If you have you answer.
