### ISSUE TITLE
Can't generate the menu items

### ISSUE THREAD

**Issue by chkilel** [Zenithar/hugo-theme-bleak#2]
I want to thank you about this wonderful theme, really I love it.
I have an issue regarding the menu, I think there is something missing in the **navigation.html** file, the `<li>` tag and the loop.
Could you please help in this.

`<div id="menu" data-target="menu">`
	`<div class="menu-header">`
		`<span class="menu-label">Menu</span>`
		`<a class="menu-close" data-action="menu" data-target="menu"></a>`
	`</div>`
	`<ul class="menu-list">`
>  ` <li class="menu-list-item">`
> `<a class="home current js-ajax-link" href="path/to/the/link">Link Title</a>`
> `</li>`

`</ul>`
`</div>`
`<div class="overlay">`
`</div>`

Many thanks

**Comment by Zenithar** [comment]
Check the new version ! I have ported all fixes from Ghost theme, and added the TOC only for page.

**Comment by chkilel** [comment]
Even after updating the theme, the navigation menu is always empty.

**Comment by Zenithar** [comment]
Ok, do you have sections in your pages / posts ? 
If not it could explain why the TOC is empty (check my own blog https://blog.zenithar.org).

**Comment by chkilel** [comment]
Many thanks Thibault for your help.

**Comment by mfioretti** [comment]
I have added my own menu with statements like this in the config file:

```
[[Languages.en.menu.main]]
  name = "About"
  url = "about"
  weight = 1
```

and now I have both that menu, AND the default menu. I can remove the corresponding code from the template, but isn't there any way to turn it off in the config. file?

Thanks

**Comment by Zenithar** [comment]
No ATM sorry.
