### ISSUE TITLE
Click on tags raises exception

### ISSUE THREAD

**Issue by HoplaGeiss** [Zenithar/hugo-theme-bleak#20]
Hello,

First of all, I love the work you did and I am also using it for my personal blog. I have a little issue when clicking on the tag on the bottom of a post. It raises an exception.

Please find attached a screenshot:
![screenshot from 2017-03-28 13-39-16](https://cloud.githubusercontent.com/assets/5755785/24405648/87dfc9ce-13bd-11e7-945f-ff83879f9553.png)

Hopefully this is a stupid mistake on my part ( it works on my local env but not when I deploy it on github )

**Comment by Zenithar** [comment]
Hello,

Have you regenerated the JS bundle ?
I checked on your website, it seems that you don't have page transition too.

**Comment by HoplaGeiss** [comment]
Do you mean doing something like this:
```
cd theme/bleak
grunt
```
If so yeah I tried it.

**Comment by Zenithar** [comment]
```
cd theme/bleak
npm/yarn install
bower install
grunt build
```

**Comment by HoplaGeiss** [comment]
Yeah, I did this as well. 
The most peculiar is that if I visit for example [http://www.muller.tech/tags/angular2/]( http://www.muller.tech/tags/angular2/) it works without problem..

**Comment by Lusitaniae** [comment]
Hi HoplaGeiss, I see that the tag urls are linking to  http://muller.tech/tags/angular2/

So the pushState fails because its linking to a different domain. Maybe some change you made to the template?

**Comment by HoplaGeiss** [comment]
@Lusitaniae you are right that fixed it! Thanks a lot :)
