### ISSUE TITLE
Requested an insecure XMLHttpRequest endpoint

### ISSUE THREAD

**Issue by izuolan** [Zenithar/hugo-theme-bleak#25]
`Mixed Content: The page at 'https://zuolan.me/mysql%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://zuolan.me/mysql%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C/'. This request has been blocked; the content must be served over HTTPS.`

How to fix this?

**Comment by Lusitaniae** [comment]
Seems OK to me. I assume you fixed it already :)

**Comment by izuolan** [comment]
There is no question of normal SSL. But if you enable HSTS, will appear the above problems, you can see here: https://zuolan.me

**Comment by Lusitaniae** [comment]
Can you try to add the baseurl param to the config file?

baseurl: https://zuolan.me/

**Comment by izuolan** [comment]
Yes, I'm sure I add the baseurl to the config file.

**Comment by Lusitaniae** [comment]
Do you include the https in the baseurl?

**Comment by izuolan** [comment]
Yes, I'm sure.

**Comment by Zenithar** [comment]
I have check on your website, it seems  to be all your screenshots are loaded via HTTP. You need to change to https to remove the warning.
