### ISSUE TITLE
subdirectory setup - pagination doesn't load

### ISSUE THREAD

**Issue by CurtTimson** [Zenithar/hugo-theme-bleak#26]
If your hugo site is set up within a subdirectory such as:

> http://domain.com/blog

The pagination links do not work correctly. They should go to:

> http://domain.com/blog/page/2

But instead they go to:

> http://domain.com/page/2

**Comment by izuolan** [comment]
Maybe the config.toml not set:
```
baseurl = "http://domain.com/blog/"
```

**Comment by CurtTimson** [comment]
I've checked this and the config is set correctly.

In my case it's:

`baseurl = "https://curttimson.github.io/curtis-timson/"`
