### ISSUE TITLE
Add custom CSS

### ISSUE THREAD

**Issue by syldor** [Zenithar/hugo-theme-bleak#29]
Thank you for this great theme ! 

I try to add a custom CSS file, I put it in static/css/custom.css and add the include in partials/header.html:

`        <link rel="preload" href="{{ .Site.BaseURL }}css/custom.css" as="style" />
`

It's working as the generated page shows the file in the source code

![image](https://cloud.githubusercontent.com/assets/4158062/24998735/74ad4f4a-203b-11e7-97eb-523e1acc1950.png)

But none of my css is taken into account in the display. What am I missing ?

**Comment by syldor** [comment]
`.test {
	color: red !important;
	text-align: center !important;
}`

and in header.html I add:
`      <p class="test">TEST</p>
`

And my test class is not taken into account.

![image](https://cloud.githubusercontent.com/assets/4158062/24998969/1f60950a-203c-11e7-8af6-59ca7b4711ac.png)

What am I missing ?

**Comment by Zenithar** [comment]
Hello,

Adding the <link> tag with rel="preload", is used to preload CSS, the file is really loaded via async loading in the main.js file.

Check https://github.com/Zenithar/hugo-theme-bleak/blob/master/src/js/script.js#L257.

PS: If you modify CSS, don't forget to regenerate criticalpath.

**Comment by syldor** [comment]
Thanks, I was indeed misusing the preload tag :)
