### ISSUE TITLE
Theme wont render

### ISSUE THREAD

**Issue by CountMurphy** [Zenithar/hugo-theme-bleak#30]
When trying to "compile" hugo throws this error:

ERROR 2017/04/14 16:35:06 Error while rendering "page": template: theme/_default/single.html:2:3: executing "theme/_default/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:64:21: executing "theme/partials/header.html" at <len .Params.tags>: error calling len: len of untyped nil 

honestly not sure if its a real bug or if I'm missing something

**Comment by Lusitaniae** [comment]
Hi @CountMurphy , seems you're missing tags for a specific page. 

Check your content pages and see if you're missing tags in any.

**Comment by CountMurphy** [comment]
You're probably correct. First time using hugo, looks like I may not know what I'm doing. I'll close this out as its clearly an issue with my setup.

**Comment by Lusitaniae** [comment]
@CountMurphy Maybe we can update the template to make the use of tags optional. 
Its about the template, not Hugo

**Comment by CountMurphy** [comment]
No need. I got it working, just didn't know what I was doing before.

**Comment by khabaroff** [comment]
Working without tags would be useful, because when you're just choosing theme and see that theme does not work, it looks like something went wrong. I really like your theme and it took time to check if updated hugo or wrong server config was the cause of errors.

**Comment by Lusitaniae** [comment]
Exactly, later today I can take a look around the template and send a PR.
