### ISSUE TITLE
Tags Page not loading

### ISSUE THREAD

**Issue by NicoHood** [Zenithar/hugo-theme-bleak#45]
If you click on the tag on the bottom of a post, the tag page does not seem to exist/load!?

**Comment by NicoHood** [comment]
@alanmcginnis If that really helps, why not open a PR for the fix?

**Comment by alanmcginnis** [comment]
@NicoHood https://github.com/Zenithar/hugo-theme-bleak/pull/52.

**Comment by NicoHood** [comment]
I did not test the PR but i assume it is fixed now.
