### ISSUE TITLE
Post image is off-center slightly to the right 

### ISSUE THREAD

**Issue by dimbula2000** [Zenithar/hugo-theme-bleak#6]
Please see the attached image taken from https://blog.zenithar.org/
![bleak-post-with-image](https://cloud.githubusercontent.com/assets/1740761/13728199/5de3e05a-e953-11e5-926e-f39975e12392.png)

**Comment by vdhatterwal** [comment]
Sorry for the off-topic comment. But I just wanted to know, what should be provided in the .md files to render posts as they render on your home page. May be some sort of link to a wiki showing examples would help a lot e.g. how to add featured image, fixed posts and other features supported. Sorry, I am just starting publishing with Hugo and your theme has particularly caught my eye.
